/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slotmachine;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Andonis
 */
public class ViewController extends javax.swing.JFrame {

    Model model;

    /**
     * Creates new form ViewController
     *
     * @param model
     */
    public ViewController(Model model) {
        
        initComponents();
        this.model = model;
        credsTxt.setText(model.getCredits());
        msgTxt.setText("Welcome!");

    }
    
    void bought(){
    msgTxt.setText("You purchased more credits! Ready to play?");
    }
    
    void displayInput(){
     msgTxt.setText("Please enter a valid, integer amount");
    }
    
    void rollingDone(int numbers[]){
    lever.revalidate();
    lever.repaint();
    lever.setIcon(new ImageIcon("C:\\Users\\Andonis\\Documents\\NetBeansProjects\\SlotMachine\\src\\slotmachine\\ezgif.com-gif-maker.gif"));
    lever.revalidate();
    lever.repaint();
    model.prize(numbers);
    credsTxt.setText(model.getCredits());
    msgTxt.setText(model.getMessage());
    spinButton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method i always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        msgText1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        spinButton1 = new javax.swing.JButton();
        credsTxt1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        spinTxt4 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        spinTxt5 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        spinTxt6 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        msgTxt = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        spinButton = new javax.swing.JButton();
        credsTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lever = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ergewf = new javax.swing.JPanel();
        Slot1 = new javax.swing.JLabel();
        eawfef = new javax.swing.JPanel();
        Slot2 = new javax.swing.JLabel();
        dwedwd = new javax.swing.JPanel();
        Slot3 = new javax.swing.JLabel();

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jPanel3.setBackground(new java.awt.Color(220, 220, 220));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 90, 65));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Slot Machine");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 15, 681, -1));

        msgText1.setColumns(20);
        msgText1.setRows(5);
        jScrollPane2.setViewportView(msgText1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 477, 340, -1));

        jLabel5.setText("Message:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 454, -1, -1));

        spinButton1.setBackground(new java.awt.Color(250, 0, 0));
        spinButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        spinButton1.setForeground(new java.awt.Color(250, 0, 0));
        spinButton1.setText("SPIN!");
        spinButton1.setToolTipText("");
        spinButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 0), 2));
        spinButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spinButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(spinButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 477, 204, 96));

        credsTxt1.setText(" ");
        credsTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credsTxt1ActionPerformed(evt);
            }
        });
        jPanel3.add(credsTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 477, 123, -1));

        jLabel6.setText("Credits:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 454, -1, -1));

        jButton3.setText("Purchase more!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 506, -1, -1));

        spinTxt4.setColumns(20);
        spinTxt4.setRows(5);
        jScrollPane7.setViewportView(spinTxt4);

        jPanel3.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 143, -1, 259));

        spinTxt5.setColumns(20);
        spinTxt5.setRows(5);
        jScrollPane8.setViewportView(spinTxt5);

        jPanel3.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 143, -1, 259));

        spinTxt6.setColumns(20);
        spinTxt6.setRows(5);
        jScrollPane9.setViewportView(spinTxt6);

        jPanel3.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 143, -1, 259));

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Slot Machine");
        setBackground(new java.awt.Color(232, 90, 65));

        jPanel1.setBackground(new java.awt.Color(232, 90, 65));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(220, 220, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 90, 65));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Slot Machine");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 15, 681, -1));

        jPanel5.setBackground(new java.awt.Color(220, 220, 220));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        msgTxt.setColumns(20);
        msgTxt.setRows(5);
        msgTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        msgTxt.setFocusable(false);
        jScrollPane14.setViewportView(msgTxt);

        jLabel10.setText("Message:");

        spinButton.setBackground(new java.awt.Color(250, 0, 0));
        spinButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        spinButton.setForeground(new java.awt.Color(250, 250, 0));
        spinButton.setText("SPIN!");
        spinButton.setToolTipText("");
        spinButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 0), 2));
        spinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spinButtonActionPerformed(evt);
            }
        });

        credsTxt.setText(" ");
        credsTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        credsTxt.setFocusable(false);
        credsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credsTxtActionPerformed(evt);
            }
        });

        jLabel11.setText("Credits:");

        jButton5.setText("Purchase more!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("Help");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lever.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slotmachine/ezgif.com-gif-maker.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(credsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(295, 295, 295)
                        .addComponent(jLabel11)))
                .addGap(3, 3, 3)
                .addComponent(spinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lever, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(credsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(spinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lever, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(220, 220, 220));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ergewf.setFocusable(false);
        ergewf.setRequestFocusEnabled(false);

        Slot1.setFont(new java.awt.Font("Tahoma", 0, 300)); // NOI18N
        Slot1.setText("$");

        javax.swing.GroupLayout ergewfLayout = new javax.swing.GroupLayout(ergewf);
        ergewf.setLayout(ergewfLayout);
        ergewfLayout.setHorizontalGroup(
            ergewfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ergewfLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ergewfLayout.setVerticalGroup(
            ergewfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        eawfef.setFocusable(false);
        eawfef.setRequestFocusEnabled(false);
        eawfef.setVerifyInputWhenFocusTarget(false);

        Slot2.setFont(new java.awt.Font("Tahoma", 0, 300)); // NOI18N
        Slot2.setText("$");

        javax.swing.GroupLayout eawfefLayout = new javax.swing.GroupLayout(eawfef);
        eawfef.setLayout(eawfefLayout);
        eawfefLayout.setHorizontalGroup(
            eawfefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eawfefLayout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        eawfefLayout.setVerticalGroup(
            eawfefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        dwedwd.setFocusable(false);
        dwedwd.setRequestFocusEnabled(false);
        dwedwd.setVerifyInputWhenFocusTarget(false);

        Slot3.setFont(new java.awt.Font("Tahoma", 0, 300)); // NOI18N
        Slot3.setText("$");

        javax.swing.GroupLayout dwedwdLayout = new javax.swing.GroupLayout(dwedwd);
        dwedwd.setLayout(dwedwdLayout);
        dwedwdLayout.setHorizontalGroup(
            dwedwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dwedwdLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dwedwdLayout.setVerticalGroup(
            dwedwdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dwedwdLayout.createSequentialGroup()
                .addComponent(Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ergewf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eawfef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dwedwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(eawfef, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ergewf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dwedwd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spinButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spinButton1ActionPerformed

    private void credsTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credsTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credsTxt1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void spinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spinButtonActionPerformed
        
        if (model.getCreditAmount() >= 25) {
            spinButton.setEnabled(false);
            lever.setIcon(new ImageIcon("C:\\Users\\Andonis\\Documents\\NetBeansProjects\\SlotMachine\\src\\slotmachine\\ezgif.com-resize (3).gif"));
            int numbers[] = model.Spin();
            msgTxt.setText("Spinning...");
            Thread  rolling = new Thread(new Rolling(Slot1, Slot2, Slot3, this, numbers));
            rolling.start();
            
//http://tutorials.jenkov.com/java-concurrency/creating-and-starting-threads.html
//            int count0 = 0;
//            int count1 = 0;
//            int count2 = 0;
            
//
//            while (count0 != numbers[0]) {
//                count0++;
//                Slot1.setText(String.valueOf(count0));
//                Slot1.repaint();
//                System.out.println(count0);
//                try {
//                    Thread.sleep(1000);
//                } catch (InterruptedException ex) {
//                    Thread.currentThread().interrupt();
//                }
//                 
//            }
//            while (count1 != numbers[1]) {
//                count1++;
//                Slot2.setText(String.valueOf(count1));
//                System.out.println(numbers[1]);
//            }
//            while (count2 != numbers[2]) {
//                count2++;
//                Slot3.setText(String.valueOf(count2));
//                System.out.println(numbers[2]);
//            }

//        
//        Slot1.setText(String.valueOf(numbers[0]));
//        Slot2.setText(String.valueOf(numbers[1]));
//        Slot3.setText(String.valueOf(numbers[2]));
//            model.prize(numbers);
//            credsTxt.setText(model.getCredits());
//            msgTxt.setText(model.getMessage());
        } else {
            msgTxt.setText("You don't have enough credits! Purchase some more!");
        }
    }//GEN-LAST:event_spinButtonActionPerformed

    private void credsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credsTxtActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        BuyDlg tab = new BuyDlg(this, true);
        tab.setVisible(true);
        if (!tab.wasCancelled()) {
            model.addCredits(tab.getCredits());
            credsTxt.setText(model.getCredits());
            
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HelpDlg tab = new HelpDlg(this, true);
        tab.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Slot1;
    private javax.swing.JLabel Slot2;
    private javax.swing.JLabel Slot3;
    private javax.swing.JTextField credsTxt;
    private javax.swing.JTextField credsTxt1;
    private javax.swing.JPanel dwedwd;
    private javax.swing.JPanel eawfef;
    private javax.swing.JPanel ergewf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel lever;
    private javax.swing.JTextArea msgText1;
    private javax.swing.JTextArea msgTxt;
    private javax.swing.JButton spinButton;
    private javax.swing.JButton spinButton1;
    private javax.swing.JTextArea spinTxt4;
    private javax.swing.JTextArea spinTxt5;
    private javax.swing.JTextArea spinTxt6;
    // End of variables declaration//GEN-END:variables
}
